name: 上报问题
description: 报告遇到的问题
labels: ['bug']
body:
  - type: checkboxes
    id: checks
    attributes:
      label: 在此之前...
      options:
      - label: 我已经搜索了现有的issues
        required: true
      - label: 我在提问题之前至少花费了5分钟来思考和准备
        required: true
      - label: 我正在使用最新版的NIKKE-scripts，否则请在下文中说明使用的版本
        required: false
  - type: textarea
    id: describe
    attributes:
      label: 问题描述
      description: 清晰地、简要地描述你遇到的问题
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: 如何复现
      description: 重现该行为的步骤
      value: |
        1. 前往 '...'
        2. 点击 '....'
        3. 滑动到 '....'
        4. 出现问题
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: 相关日志
      description: |
        相关的日志输出
        提示：该文本框可以上传图片
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: 出错截图
      description: |
        添加屏幕截图以帮助解释你的问题
        提示：该文本框可以上传图片，脚本v0.8版本后可在`./images/nikkerror`下找到出错截屏
    validations:
      required: false
  - type: textarea
    id: others
    attributes:
      label: 其他内容
      description: 其他你认为有价值的信息
    validations:
      required: false