name: Level Infinite pass 签到

on: 
  # schedule:
  #   - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: pip
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ./NIKKE/tools/
    - name: Ensure browsers are installed
      run: python -m playwright install chromium --with-deps
    - name: Run python script
      run: |
        python pass-checkin.py ${{ secrets.GAME_EMAIL }} ${{ secrets.GAME_PASSWORD }}
      working-directory: ./NIKKE/tools/
