name: 获取咨询文本

on: 
  schedule:
    - cron:  '0 0 */3 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
    - uses: actions/checkout@v3
      with:
        ref: dev
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: pip
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ./NIKKE/tools/
    - name: Run python script
      run: |
        python fetch_answers.py ${{ secrets.GOOGLE_API_KEY }}
      working-directory: ./NIKKE/tools/
    - name: Commit nikke.json file if changed
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 更新nikke.json
        repository: ./NIKKE
        file_pattern: nikke.json
